{
  "hash": "eb14260ce3196558e05d8c3a0844e623",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"RPA 生存路径的耗时：校正 Cox 曲线、HR 与时点生存率\"\nsubtitle: \"get_rpa → get_cat 各步骤在 4387 到 100000 例下的耗时和内存，以及已并入 RegR 的两项优化\"\ndate: 2026-10-02\n---\n\n\n\n评估对象是 RegR 0.1.3 中 `get_rpa()` 的生存路径（`surv = TRUE`）。传入 `adj_var` 后，`get_rpa()` 在终末节点分组上调用一次：\n\n```r\nget_cat(dat, cat_var = \"group\", adj_var = adj_var, surv = TRUE,\n        timepoint = 120, methods_obj = c(\"unadj\", \"direct\"))\n```\n\n`get_cat()` 的结果由三块组成，本页分别计时：\n\n| 组成部分 | 内部调用 | 在 RPA 图表中的位置 |\n|:--|:--|:--|\n| `cat$obj` 曲线 | `.get.obj(times = NULL)` → `adjustedCurves::adjustedsurv()`，未调整用 `\"km\"`，调整用 `\"direct\"` | `plt_rpa_km()` 左右两列、`plt.sur`、`plt.rpa1`、`plt.rpa2` |\n| `cat$UM` 的 haz 表 | `.get.UM.haz()` → `survival::coxph()` | HR1 / HR2 |\n| `cat$UM` 的 sur 表 | `.get.UM.sur(time = 120)` → `.get.obj(times = 120)` | SP1 / SD1、SP2 / SD2 |\n\n: get_cat 的组成和对应的耗时单元。 {#tbl-parts}\n\n`\"direct\"` 是直接标准化（g-computation）：先拟合 `Surv(time, DSS) ~ group + adj_var` 的 Cox 模型，再把每个人分别放进每一组预测生存曲线，然后取平均。置信区间由 `riskRegression::ate()` 的影响函数给出。\n\n## 结论\n\n1. **慢的只有调整后的生存曲线。**n = 4387 时整个 `get_cat()` 用了 18.3 s，其中调整后的曲线占 17.4 s。HR 表在 n = 100000 时也只要 0.7 s；120 个月生存率表（含调整）在 n = 100000 时要 14 s；未调整的 KM 曲线始终不超过 1.7 s。\n2. **调整后曲线随 n 增长很快。**n = 15000、30000、50000 时分别要 65 s、160 s、262 s，峰值内存 6.6、11.2、18.6 GB。按 8000 到 50000 拟合，耗时约按 n^1.25^ 增长，内存基本与 n 成正比。外推到 n = 100000 约需 10 分钟、37 GB 内存（未实测）。\n3. **耗时几乎都花在置信区间上。**同样的调整曲线不求置信区间（`conf_int = FALSE`）时，n = 50000 也只要 6.7 s。\n4. **根源是 `ate()` 默认计算所有组之间的两两对比。**11 个组共 55 对，每对都要在约 157 个事件时间上算影响函数；adjustedCurves 实际只用到各组自己的平均生存率。改成\"参照组对其余各组\"的 10 对后，n = 8000 时从 40.6 s 降到 7.7 s，11 个组在所有时间点上的生存率、标准误和置信区间与默认结果完全相同。\n5. **减少时间点也有效。**曲线改为每 6 个月取一个点，n = 8000 时从 35 s 降到 5.7 s，n = 30000 时从 145 s 降到 18 s；120 个月处的估计值和置信区间不变，但曲线变粗。\n6. **方案 A 和改良后的方案 B 已于 2026-10-02 并入 RegR。**B 改成了「最多 50 个时间点，按事件时间抽取」。11 组、n = 30000 的 `get_cat()` 从 171 s 降到 14 s；保留下来的每个时间点上，曲线、标准误和置信区间与原来完全相同，HR 和生存率表一字不差。A 同样用于竞争风险的 CSC 模型；FGR 不经过 `ate()`，A 对它不适用，B 也没有让它变快。见「已并入 RegR 的优化」。\n\n## 测试设置\n\n- **环境：**Windows 11，Intel Core Ultra 9 275HX（24 逻辑核），128 GB 内存；R 4.4.3，RegR 0.1.3（Windows R 安装版），adjustedCurves 0.11.4，riskRegression 2025.5.20，survival 3.8.12。注意：[竞争风险 CIF 基准](get-eff-cif-benchmark.qmd)是在 WSL 上测的，环境不同，两页的绝对耗时不能直接比较。\n- **数据：**`RegR::seer_thyroid_mtc_2026`，n = 4387，DSS 事件 597 个。先在完整数据上运行 `get_rpa(d, c(\"Age\", \"T_stage\"), adj_var = \"Sex\", surv = TRUE)`，得到 11 个终末节点分组；更大的 n 对这份带分组的数据按行有放回重抽样（表中标 \\*），因此事件时间点始终是同样的 157 个。真实的大队列通常有更多不同的事件时间，调整曲线的耗时会更高。\n- **调整变量：**只有 `Sex`。\n- **计时：**每个单元只跑一次，记录 `system.time()` 的墙钟时间；峰值内存取 `gc(reset = TRUE)` 之后 `gc()` 的 \"max used\"，只统计 R 堆内存。只有一个分组变量时，RegR 的外层不会并行，所有调用都是单进程。\n- **波动：**同一份 n = 8000 数据上，同一个调整曲线调用先后测到 26–41 s。表中数字只用来看量级和增长趋势。\n\n## 耗时结果\n\n\n::: {.cell renderings='[\"light\",\"dark\"]'}\n::: {.cell-output-display}\n![各步骤的墙钟耗时（秒），双对数坐标。虚线右侧为重抽样放大的样本。n = 100000 时没有测调整后的曲线。](rpa-cox-benchmark_files/figure-html/fig-timing-1.png){#fig-timing-1 width=720}\n:::\n\n::: {.cell-output-display}\n![各步骤的墙钟耗时（秒），双对数坐标。虚线右侧为重抽样放大的样本。n = 100000 时没有测调整后的曲线。](rpa-cox-benchmark_files/figure-html/fig-timing-2.png){#fig-timing-2 width=720}\n:::\n:::\n\n\n::: {.nowrap .column-page}\n\n\n::: {#tbl-timing .cell tbl-cap='各步骤墙钟耗时（秒）与调整曲线的峰值内存（GB）。“曲线”是整个随访期的曲线（cat$obj），“120 月”是 timepoint = 120 的生存率与生存率差表。'}\n::: {.cell-output-display}\n\n\n|         n| KM 曲线|  调整曲线| 其内存| 调整曲线（不带 CI）| HR 未调整| HR 调整| 120 月 未调整| 120 月 调整|\n|---------:|-------:|---------:|------:|-------------------:|---------:|-------:|-------------:|-----------:|\n|     4,387|    1.53|  **18.9**|    2.1|                0.65|      0.17|    0.05|          0.11|        1.32|\n|   8,000\\*|    0.13|  **26.6**|    3.1|                1.08|      0.07|    0.04|          0.08|        1.55|\n|  15,000\\*|    0.16|  **64.6**|    6.6|                1.79|      0.11|    0.08|          0.13|        2.32|\n|  30,000\\*|    1.58| **159.6**|   11.2|                3.33|      0.22|    0.14|          0.15|        3.78|\n|  50,000\\*|    0.17| **262.2**|   18.6|                6.67|      0.25|    0.21|          0.15|        6.07|\n| 100,000\\*|    1.69|  **未测**|      —|                15.3|      0.73|    0.72|          0.50|        14.2|\n\n\n:::\n:::\n\n\n:::\n\n\n\n另外在 n = 4387 上测了一次完整的 `get_cat()`：18.3 s，其中调整曲线这一步 17.4 s。`.get.obj()` 在 `times = NULL` 时还会打印一张诊断曲线图，直接调 `adjustedsurv()` 的耗时（`as_direct_CI`，见 CSV）比经过 RegR 包装的版本少 1–10 s，主要是这部分画图和包装开销，也夹杂了计时波动。\n\n## 慢在哪里\n\n调整曲线走的是 adjustedCurves 内部的 `surv_direct()`，Cox 模型在这里直接交给 `riskRegression::ate()`：\n\n```r\nsurv <- riskRegression::ate(event = outcome_model, treatment = variable,\n                            data = data, estimator = \"Gformula\", times = times,\n                            se = conf_int, verbose = verbose, cause = 1, ...)\n```\n\n`times = NULL` 时，`times` 是全部事件时间（本数据 157 个）。`ate()` 的 `allContrasts` 默认取所有组的两两组合，11 个组就是 55 对，每对的风险差和风险比都要算影响函数。adjustedCurves 只读取其中的 `meanRisk`（各组自己的平均风险），两两对比算完就丢掉了。\n\n`adjustedsurv()` 会把 `...` 原样传给 `ate()`，所以可以从外面指定只算\"参照组对其余各组\"：\n\n\n::: {#tbl-contrast .cell tbl-cap='n = 8000，同一份数据、同一个 Cox 模型，只改 ate() 的 allContrasts。'}\n::: {.cell-output-display}\n\n\n|allContrasts                     | 耗时（s）| 输出行数|与默认结果比较                                   |\n|:--------------------------------|---------:|--------:|:------------------------------------------------|\n|默认：所有两两组合（55 对）      |      40.6|     1595|—                                                |\n|rbind(参照组, 其余各组)（10 对） |       7.7|     1595|11 组 × 全部时间点的 surv、se、CI 最大差值均为 0 |\n\n\n:::\n:::\n\n\n如果只传一对（`matrix(lv[1:2], nrow = 2)`），耗时会降到 1 s 左右，但 `ate()` 只输出这两个组，其余 9 组的曲线没了，所以不能这样用。\n\n## 减少时间点\n\n\n::: {#tbl-grid .cell tbl-cap='带置信区间的调整曲线在不同时间网格下的耗时。最右列是第 1 组在 120 个月处的生存率（95% CI）。'}\n::: {.cell-output-display}\n\n\n|      n|时间网格                   | 时间点 × 组| 耗时（s）| 峰值内存（GB）|          S(120) 第 1 组|\n|------:|:--------------------------|-----------:|---------:|--------------:|-----------------------:|\n|  8,000|全部事件时间（现在的做法） |        1595|      35.2|            2.9| 0.9756 (0.9682, 0.9830)|\n|  8,000|seq(0, 240, by = 6)        |         451|       5.7|            1.1| 0.9756 (0.9682, 0.9830)|\n|  8,000|seq(0, 240, by = 12)       |         231|       3.4|            0.7| 0.9756 (0.9682, 0.9830)|\n| 30,000|全部事件时间（现在的做法） |        1738|     144.8|           13.3| 0.9728 (0.9687, 0.9770)|\n| 30,000|seq(0, 240, by = 6)        |         451|      18.1|            3.7| 0.9728 (0.9687, 0.9770)|\n| 30,000|seq(0, 240, by = 12)       |         231|       9.9|            2.0| 0.9728 (0.9687, 0.9770)|\n\n\n:::\n:::\n\n\n`ate()` 在每个时间点上的估计互不依赖，所以只要 120 个月仍在网格里，该点的估计和置信区间就与全部事件时间时完全相同。代价是曲线从 145–158 个点降到 41 个（每 6 个月）或 21 个（每 12 个月），图形会变粗。\n\n## 已并入 RegR 的优化（A + B）\n\n2026-10-02 起，下面两项已并入 RegR（版本号仍是 0.1.3，对应提交 `63541f6`、`c71fe16`、`c1f6435`）。本节的「改动前 / 改动后」都在同一台机器、同一份数据上，用 Windows R 先后装两个版本各跑一次 `get_cat(..., timepoint = 120)`，环境同「测试设置」。\n\n| 优化 | 改了什么 | 作用范围 | 对结果的影响 |\n|:--|:--|:--|:--|\n| A | `.get.obj()` 的 direct 分支给 `adjustedsurv()` / `adjustedcif()` 传 `allContrasts = rbind(参照组, 其余各组)` | Cox 调整生存曲线；竞争风险 `cif_args = list(model = \"CSC\")` 的调整 CIF；也包括走同一函数的 120 月生存率（CIF）表 | 无。每组的估计、标准误、CI 与默认的两两对比完全相同 |\n| B | `get_cat()` 的调整曲线最多保留 50 个时间点：从全部事件时间中均匀抽 48 个，再加上 0 和 `timepoint` | `cat$obj$direct`，Cox 与竞争风险（CSC、FGR）都适用，因此覆盖 `get_rpa()`、`plt_cat1/2/3()`、`plt_rpa_km()` | 保留的时间点上数值完全相同；点与点之间的连线最多偏离约 1 个百分点 |\n\n: 已实施的两项优化。 {#tbl-applied}\n\n不受影响的部分：\n\n- KM、IPTW、匹配曲线照常使用全部事件时间：它们本来就快，而且 KM 要画成阶梯。\n- B 只加在 `get_cat()` 这一层，没有放进 `.get.obj()`。原因是 `get_facet_diff()` 会从 `times = NULL` 的曲线对象上读取 60、120、180 个月的数值，抽点会改变这些数。所以 `get_facet()` 和 `get_facet_diff()` 的曲线不变。\n- direct 方法失败而回退到 KM 时，回退曲线仍使用全部事件时间。抽点网格通过内部参数 `.get.obj(direct_times = )` 传入，只对 direct 方法生效。\n- 从 `cat$obj$direct` 自行计算中位生存时间或 RMST 时，结果现在是近似值。\n\n\n\n合计效果以 11 组 Cox、n = 30000 为例：`get_cat()` 原来 171 s，加上 A 后 50 s（另一轮测得 49 s），再加上 B 后 14 s，前后约快 12 倍。\n\n### 方案 A：只算参照组对其余各组\n\n\n::: {#tbl-a-cox .cell tbl-cap='方案 A 前后的 get_cat()（Cox）。结果比较包括：调整与未调整曲线的生存率、se、CI 最大差值为 0；HR / 生存率四张表和 2 组时的多时点生存率差表 identical()；去掉 obj$call 后整个结果 all.equal() 为 TRUE（新版 call 里多了 allContrasts）。'}\n::: {.cell-output-display}\n\n\n|场景                     |      n| 改动前（s）| 改动后（s）|结果比较                          |\n|:------------------------|------:|-----------:|-----------:|:---------------------------------|\n|11 组，按 Sex 调整       |  4,387|        23.3|        10.8|完全相同                          |\n|11 组，按 Sex 调整       | 30,000|       171.0|        50.3|完全相同                          |\n|2 组（Sex），按 Age 调整 |  4,387|         1.4|         1.3|完全相同（只有 1 对，没有可省的） |\n\n\n:::\n:::\n\n\n竞争风险的 CSC 模型同样走 `ate()`。adjustedCurves 的 `cif_direct()` 在 `outcome_model` 是 `CauseSpecificCox` 时调用 `ate()`，其余模型（包括 FGR）改走 `cif_g_comp()`。所以 A 只加在 CSC 上，FGR 不传这个参数。\n\n\n::: {#tbl-a-csc .cell tbl-cap='方案 A 用于 CSC：直接调 adjustedcif(method = \"direct\")，n = 4387，11 组，按 Sex 调整。'}\n::: {.cell-output-display}\n\n\n|时间点              |allContrasts              | 耗时（s）| 峰值内存（GB）| 输出行数|与默认结果比较         |\n|:-------------------|:-------------------------|---------:|--------------:|--------:|:----------------------|\n|全部 227 个事件时间 |默认（55 对）             |     28.58|           2.90|     2497|—                      |\n|全部 227 个事件时间 |参照组对其余各组（10 对） |      7.64|           1.69|     2497|CIF、se、CI 最大差值 0 |\n|方案 B 的 50 个点   |默认（55 对）             |      4.75|           0.83|      550|—                      |\n|方案 B 的 50 个点   |参照组对其余各组（10 对） |      2.59|           0.47|      550|CIF、se、CI 最大差值 0 |\n\n\n:::\n:::\n\n\n\n\n放到整个 `get_cat(surv = FALSE, cif_args = list(model = \"CSC\"))` 里（已含方案 B），n = 4387 时从 10.1 s 降到 5.8 s，n = 30000 时只从 102.3 s 降到 93.4 s。CIF、标准误、CI 和所有表格都与改动前完全相同。n = 30000 时提速不明显，原因见本节最后一小节。\n\n### 方案 B：最多 50 个时间点\n\n先比较了几种取点方式。调整曲线本来就画成折线（`steps = FALSE`），所以用「抽点后的折线」和「完整曲线」在全部事件时间上的最大差值，来衡量画出来的偏移。\n\n\n::: {#tbl-b-grid .cell tbl-cap='不同时间网格下带置信区间的调整曲线（Cox，11 组，已含方案 A）。偏移以百分点计，0.01 即 1 个百分点。这里的抽点网格是 0 加 49 个事件时间；实施版本是 48 个事件时间加 0 和 timepoint。'}\n::: {.cell-output-display}\n\n\n|      n|时间网格                     | 耗时（s）| 峰值内存（GB）| 曲线最大偏移| CI 下限偏移| CI 上限偏移|\n|------:|:----------------------------|---------:|--------------:|------------:|-----------:|-----------:|\n|  4,387|全部事件时间（158 个）       |       8.8|            0.8|            —|           —|           —|\n|  4,387|按事件时间均匀抽 50 个       |       2.0|            0.5|         0.79|        0.94|        0.64|\n|  4,387|0 到最后事件时间等间距 50 个 |       1.7|            0.6|         1.34|        2.03|        1.03|\n|  4,387|等间距 25 个                 |       1.2|            0.5|         2.03|        3.04|        1.01|\n| 30,000|全部事件时间（158 个）       |      44.8|            3.9|            —|           —|           —|\n| 30,000|按事件时间均匀抽 50 个       |       9.2|            1.6|         1.09|        1.16|        1.05|\n| 30,000|0 到最后事件时间等间距 50 个 |       9.4|            2.1|         1.31|        1.49|        1.17|\n| 30,000|等间距 25 个                 |       5.6|            1.1|         2.11|        2.49|        1.73|\n| 50,000|全部事件时间（158 个）       |      76.2|            5.9|            —|           —|           —|\n| 50,000|按事件时间均匀抽 50 个       |      15.2|            2.8|         0.80|        0.84|        0.76|\n| 50,000|0 到最后事件时间等间距 50 个 |      15.2|            3.1|         1.23|        1.48|        1.17|\n| 50,000|等间距 25 个                 |      10.1|            1.5|         1.97|        2.27|        1.66|\n\n\n:::\n:::\n\n\n按事件时间抽点比等间距更准，因为事件密集的早期取的点也多。实施时选了这种方式，并补上 `timepoint`，让曲线在 120 个月处与生存率表的数值一致。所有方式在保留的时间点上都与完整计算完全相同：`ate()` 在每个时间点上的估计互不依赖。\n\n![n = 4387 时 11 组的调整生存曲线。黑色实线为全部 158 个事件时间，红色虚线为按事件时间抽的 50 个点，蓝色点线为等间距 50 个点，灰色带为完整曲线的 95% CI。三条线在这个尺寸下几乎重合。](images/rpa-cox-benchmark/grid-compare.png){#fig-grid}\n\n\n::: {#tbl-b-getcat .cell tbl-cap='方案 B 前后的 get_cat()（11 组，按 Sex 调整，已含方案 A）。四个场景的 HR / 生存率（CIF）表和未调整曲线都与改动前 identical()。'}\n::: {.cell-output-display}\n\n\n|模型           |n      | 调整曲线时间点| 改动前（s）| 改动后（s）| 保留点上的差值|曲线最大偏移（百分点） |\n|:--------------|:------|--------------:|-----------:|-----------:|--------------:|:----------------------|\n|Cox            |4,387  |       158 → 50|         6.1|         6.7|              0|0.79（CI 0.94 / 0.64） |\n|Cox            |30,000 |       158 → 50|        48.8|        14.2|              0|1.09（CI 1.16 / 1.05） |\n|竞争风险 · CSC |4,387  |       227 → 50|        32.2|         9.7|              0|0.95（CI 0.79 / 1.11） |\n|竞争风险 · FGR |4,387  |       227 → 50|        69.5|        70.2|              0|0.83                   |\n\n\n:::\n:::\n\n\nFGR 的置信区间来自 bootstrap（`boot_adj`），在 50 个保留点上与改动前的差值也是 0。但 FGR **没有变快**：它的时间花在 50 次 bootstrap 重新拟合 Fine-Gray 模型上，与要预测多少个时间点关系不大。n = 4387 的 Cox 也看不出差别，因为这时调整曲线已经不是主要耗时（见「局限」）。\n\n### n = 30000 的竞争风险还慢在哪里\n\n\n::: {#tbl-csc-parts .cell tbl-cap='n = 30000、11 组、cif_args = list(model = \"CSC\") 时 get_cat() 各步骤的耗时（A + B 都已实施）。'}\n::: {.cell-output-display}\n\n\n|步骤                              | 耗时（s）| 占比|\n|:---------------------------------|---------:|----:|\n|HR · 调整（Fine-Gray crr）        |      29.6|  33%|\n|HR · 未调整（Fine-Gray crr）      |      26.6|  30%|\n|调整 CIF 曲线（CSC，50 个点）     |      21.3|  24%|\n|120 月 CIF · 调整（CSC）          |      10.9|  12%|\n|未调整 CIF 曲线（Aalen-Johansen） |       1.7|   2%|\n|120 月 CIF · 未调整               |       0.1|   0%|\n\n\n:::\n:::\n\n\n不论 `cif_args` 选哪个模型，竞争风险的 HR 都用 Fine-Gray（`crr`）计算。两次 `crr` 拟合加起来占了六成，是现在的主要瓶颈，A 和 B 都不涉及这一步。\n\n## 可选的改进\n\n下表是最初评估时列出的做法。A 已原样实施；B 实施时改成了「最多 50 个时间点、按事件时间抽取」，见上一节；C 和 D 没有采用。\n\n| 方案 | 改什么 | 提速 | 代价 |\n|:--|:--|:--|:--|\n| A | 在 `.get.obj()` 的 direct 生存分支给 `adjustedsurv()` 加 `allContrasts = rbind(参照组, 其余各组)` | 调整曲线约 5 倍（n = 8000 实测）；120 月生存率表走同一个函数，预计也会受益，但没有单独测 | 结果完全相同，返回结构不变 |\n| B | 调整曲线改用每 6 个月一个点的时间网格 | 6–8 倍 | 曲线点数从 145–158 降到 41，图形变粗 |\n| C | 调整曲线不画置信带（`conf_int = FALSE`） | 25–48 倍 | 图上没有置信带 |\n| D | 不改 | — | n = 50000 时一次 `get_rpa()` 光调整曲线就要约 4.5 分钟、19 GB 内存 |\n\n: 加速调整曲线的几种做法（最初评估时的版本）。A 和 B 叠加后的实测效果见上一节。 {#tbl-options}\n\n## 局限\n\n- 只在 Windows R 上测了一次，每个单元只跑一次，耗时有约 ±25% 的波动。\n- 只测了 11 个分组、1 个调整变量的情形。两两对比的数量是 k(k−1)/2，分组越多，方案 A 的收益越大；只有 2 个组时只有 1 对，方案 A 没有作用。\n- n > 4387 的数据是重抽样放大的，事件时间点固定为 157 个，只能用来看耗时的增长趋势，不能拿来解释效应大小。\n- 没有计时 `get_rpa()` 里的建树（`partykit::ctree`）和拼图部分。\n- 峰值内存只统计 R 堆，不含 R 之外的分配。\n- 优化前后的对比每个场景也只跑一次。n = 4387 时整个 `get_cat()` 只要几秒到十几秒，其中包括首次加载包的开销：同一个版本在两轮里分别测得 10.8 s 和 6.1 s，所以小样本的前后差别看不出来。\n- 方案 B 只在 11 组、事件时间以整月计（最多两三百个不同时间）的数据上评估过。时间以天计的数据会有上千个事件时间，B 的收益会更大，但没有实测。\n\n## 复现脚本\n\n脚本在 Windows R 的 Rscript 下运行，输出写到当前工作目录。本页图表直接读取 [`regr/bench/`](https://github.com/HUI950319/Rnotes/tree/main/regr/bench) 下的 `rpa_cox_timing.csv`（计时矩阵；`run = \"pilot\"` 是包含完整 `get_cat()` 的初测）和 `rpa_cox_knobs.csv`（`ate()` 两个开关的试验）。这些文件只有汇总结果，不含个体数据。\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"rpa_cox_bench.R：计时矩阵与 ate() 开关试验\"}\n# RPA 生存路径中 Cox 曲线 / HR / 时点生存率的耗时基准（Windows R 4.4.3）\n#\n# 用法：\n#   Rscript rpa_cox_bench.R timing 4387,8000,15000      # 第 1 部分：计时矩阵\n#   BENCH_ONLY=curve_direct,SP_direct Rscript rpa_cox_bench.R timing 30000,50000\n#   Rscript rpa_cox_bench.R knobs                       # 第 2 部分：ate() 的两个开关\n# 输出写到当前目录：bench_<sizes>.csv；knobs 结果打印到 stderr。\n\nargs <- commandArgs(TRUE)\nmode <- args[1]\nsuppressPackageStartupMessages({ library(RegR); library(survival) })\npdf(NULL)  # 吞掉 get_rpa() / .get.obj() 自带的 print(plot(...))\n\n## ---- 0. 基础数据：在完整 4387 例上跑一次 get_rpa()，取 RPA 分组 --------------\nbase_rds <- \"base_rpa.rds\"\nif (!file.exists(base_rds)) {\n  data(seer_thyroid_mtc_2026, package = \"RegR\")\n  sink(nullfile())\n  res <- suppressWarnings(get_rpa(seer_thyroid_mtc_2026, c(\"Age\", \"T_stage\"),\n                                  adj_var = \"Sex\", surv = TRUE))\n  sink()\n  b <- res$dat[, c(\"time\", \"DSS\", \"group\", \"Sex\", \"Age\")]\n  saveRDS(b[stats::complete.cases(b), ], base_rds)\n}\nbase <- readRDS(base_rds)   # n = 4387，597 个事件，11 个 RPA 组\n\n## ---- 1. 计时矩阵 ---------------------------------------------------------------\nif (identical(mode, \"timing\")) {\n  sizes <- as.integer(strsplit(args[2], \",\")[[1]])\n\n  timeit <- function(expr) {\n    invisible(gc(reset = TRUE))\n    t <- system.time(r <- tryCatch({ force(expr); \"ok\" },\n                                   error = function(e) paste(\"ERR:\", conditionMessage(e))))[[\"elapsed\"]]\n    list(sec = t, mb = sum(gc()[, 6]), status = r)   # gc() \"max used\"（MB）\n  }\n  cox <- function(d) coxph(Surv(time, DSS) ~ group + Sex, data = d, x = TRUE)\n  cells <- list(\n    # get_cat() 的 cat$obj：整条曲线（times = NULL）\n    curve_unadj    = function(d) RegR:::.get.obj(d, \"group\", \"Sex\", method = \"unadj\",  times = NULL, allow_fallback = FALSE),\n    curve_direct   = function(d) RegR:::.get.obj(d, \"group\", \"Sex\", method = \"direct\", times = NULL, allow_fallback = FALSE),\n    # get_cat() 内部 get_eff() 的 haz 表（HR）\n    HR_unadj       = function(d) RegR:::.get.UM.haz(d, \"group\", adj_var = \"Sex\", method = \"unadj\"),\n    HR_direct      = function(d) RegR:::.get.UM.haz(d, \"group\", adj_var = \"Sex\", method = \"direct\"),\n    # get_cat() 内部 get_eff() 的 sur 表（timepoint = 120 的 S(t) 与 ΔS(t)）\n    SP_unadj       = function(d) RegR:::.get.UM.sur(d, \"group\", adj_var = \"Sex\", method = \"unadj\",  time = 120),\n    SP_direct      = function(d) RegR:::.get.UM.sur(d, \"group\", adj_var = \"Sex\", method = \"direct\", time = 120),\n    # 拆分：只调 adjustedsurv(direct)，不经 RegR 包装、不画图\n    as_direct_CI   = function(d) adjustedCurves::adjustedsurv(d, variable = \"group\", ev_time = \"time\", event = \"DSS\",\n                                   method = \"direct\", conf_int = TRUE,  outcome_model = cox(d)),\n    as_direct_noCI = function(d) adjustedCurves::adjustedsurv(d, variable = \"group\", ev_time = \"time\", event = \"DSS\",\n                                   method = \"direct\", conf_int = FALSE, outcome_model = cox(d)),\n    # 整个 get_cat()（与 get_rpa() 生存路径的调用一致）\n    get_cat_total  = function(d) get_cat(d, cat_var = \"group\", adj_var = \"Sex\", surv = TRUE,\n                                         timepoint = 120, methods_obj = c(\"unadj\", \"direct\"))\n  )\n  only <- Sys.getenv(\"BENCH_ONLY\")\n  if (nzchar(only)) cells <- cells[strsplit(only, \",\")[[1]]]\n\n  out <- list()\n  set.seed(2026)\n  for (n in sizes) {\n    # n = 4387 用原数据；更大的 n 按行有放回重抽样（时间网格不变，最多 157 个事件时间）\n    d <- if (n == nrow(base)) base else base[sample.int(nrow(base), n, replace = TRUE), ]\n    for (nm in names(cells)) {\n      sink(nullfile()); r <- timeit(cells[[nm]](d)); sink()\n      message(sprintf(\"n=%7d  %-14s %8.2f s  peak %7.0f MB  %s\", n, nm, r$sec, r$mb, r$status))\n      out[[length(out) + 1]] <- data.frame(n = n, cell = nm, sec = r$sec, peak_mb = r$mb, status = r$status)\n    }\n    write.csv(do.call(rbind, out), sprintf(\"bench_%s.csv\", paste(sizes, collapse = \"_\")), row.names = FALSE)\n  }\n}\n\n## ---- 2. riskRegression::ate() 的两个开关 ----------------------------------------\n# adjustedsurv(method = \"direct\") 把 ... 原样转给 ate()，所以 times / allContrasts 都能从外面传进去。\nif (identical(mode, \"knobs\")) {\n  go <- function(d, fit, ...) {\n    invisible(gc(reset = TRUE))\n    t <- system.time(o <- adjustedCurves::adjustedsurv(d, variable = \"group\", ev_time = \"time\", event = \"DSS\",\n                       method = \"direct\", conf_int = TRUE, outcome_model = fit, ...))[[\"elapsed\"]]\n    list(t = t, mb = sum(gc()[, 6]), pd = o$adj)\n  }\n  key <- function(p) p[order(p$group, p$time), c(\"time\", \"group\", \"surv\", \"se\", \"ci_lower\", \"ci_upper\")]\n\n  # 2a. 时间网格：全部事件时间 vs 每 6 / 12 个月；顺带试只算 1 对对比\n  set.seed(2026)\n  for (n in c(8000, 30000)) {\n    d <- base[sample.int(nrow(base), n, replace = TRUE), ]; lv <- levels(d$group)\n    fit <- coxph(Surv(time, DSS) ~ group + Sex, data = d, x = TRUE)\n    for (s in list(list(lab = \"all_event_times\"),\n                   list(lab = \"allContrasts_1pair\", allContrasts = matrix(lv[1:2], nrow = 2)),\n                   list(lab = \"times_by_6\",  times = seq(0, 240, by = 6)),\n                   list(lab = \"times_by_12\", times = seq(0, 240, by = 12)))) {\n      r <- do.call(go, c(list(d = d, fit = fit), s[-1]))\n      g1 <- r$pd[r$pd$group == lv[1] & r$pd$time == 120, ]\n      message(sprintf(\"n=%6d %-20s %7.2f s  peak %6.0f MB  rows=%5d  S(120)[g1]=%.4f CI=[%.4f, %.4f]\",\n                      n, s$lab, r$t, r$mb, nrow(r$pd), g1$surv, g1$ci_lower, g1$ci_upper))\n    }\n  }\n\n  # 2b. 全部 55 对（默认）vs 参照组对其余各组 10 对：结果是否完全相同\n  set.seed(2026)\n  d <- base[sample.int(nrow(base), 8000, replace = TRUE), ]; lv <- levels(d$group)\n  fit <- coxph(Surv(time, DSS) ~ group + Sex, data = d, x = TRUE)\n  a <- go(d, fit)\n  v <- go(d, fit, contrasts = lv, allContrasts = rbind(lv[1], lv[-1]))\n  A <- key(a$pd); V <- key(v$pd)\n  message(sprintf(\"all pairs %.2f s | ref-vs-each %.2f s | same rows: %s | max|diff| surv=%.1e se=%.1e ci=%.1e\",\n                  a$t, v$t, identical(A[, 1:2], V[, 1:2]), max(abs(A$surv - V$surv)), max(abs(A$se - V$se)),\n                  max(abs(c(A$ci_lower - V$ci_lower, A$ci_upper - V$ci_upper)))))\n}\n```\n:::\n\n\n「已并入 RegR 的优化」一节读取 `rpa_cox_optim.csv`，其中只有汇总结果。产生这些数字的几个独立脚本按运行顺序原样收录在 `rpa_cox_optim.R` 里，每段单独保存成 .R 后运行；文件开头写明了每段的 before / after 各对应哪个 RegR 版本。\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"rpa_cox_optim.R：方案 A / B 的前后对比\"}\n# RPA 生存路径：方案 A（只算参照组对比）与方案 B（最多 50 个时间点）的前后对比\n#\n# 以下是实际运行过的独立脚本，按运行顺序原样收录；每段单独存成 .R，在 Windows R 的\n# Rscript 下运行。base_rpa.rds 由 rpa_cox_bench.R 第 0 部分生成；base2.rds 由第 3 段\n# 自己生成（多保留 event / status 两列，供竞争风险使用）。\n# \"before\" / \"after\" 指先后安装的两个 RegR 版本：\n#   第 1 段 before = A 之前，after = 63541f6（A，Cox）\n#   第 3 段 before = 63541f6，after = c71fe16（B）\n#   第 5 段 before = c71fe16，after = c1f6435（A，CSC）；脚本即第 3 段只保留两个 CSC 场景、\n#           文件前缀改为 before3_ / after3_\n# 汇总结果写在 rpa_cox_optim.csv。\n\n\n## ==== 第 1 段：方案 A，Cox get_cat 前后对比（ab_run.R <before|after>）\n\n# Usage: Rscript ab_run.R <tag>   (tag = before | after)\ntag <- commandArgs(TRUE)[1]\nsuppressPackageStartupMessages(library(RegR))\npdf(NULL)\nbase <- readRDS(\"base_rpa.rds\")\nset.seed(2026); big <- base[sample.int(nrow(base), 30000, replace = TRUE), ]\ncases <- list(\n  rpa11_n4387  = list(d = base, cat = \"group\", adj = \"Sex\"),\n  rpa11_n30000 = list(d = big,  cat = \"group\", adj = \"Sex\"),\n  sex2_n4387   = list(d = base, cat = \"Sex\",   adj = \"Age\")\n)\nmessage(sprintf(\"[%s] RegR loaded from %s\", tag, find.package(\"RegR\")))\nfor (nm in names(cases)) {\n  cs <- cases[[nm]]\n  sink(nullfile())\n  t <- system.time(res <- suppressWarnings(get_cat(cs$d, cat_var = cs$cat, adj_var = cs$adj,\n                     surv = TRUE, timepoint = 120)))[[\"elapsed\"]]\n  sink()\n  saveRDS(res, sprintf(\"%s_%s.rds\", tag, nm))\n  message(sprintf(\"[%s] %-14s get_cat %7.2f s\", tag, nm, t))\n}\n\n## ---- 第 1 段比较（ab_compare.R）\n\nsuppressPackageStartupMessages(library(RegR))\nstrip <- function(cat) { cat$obj <- lapply(cat$obj, function(o) { o$call <- NULL; o }); cat }\nfor (nm in c(\"rpa11_n4387\", \"rpa11_n30000\", \"sex2_n4387\")) {\n  b <- readRDS(sprintf(\"before_%s.rds\", nm))$cat\n  a <- readRDS(sprintf(\"after_%s.rds\",  nm))$cat\n  cat(sprintf(\"\\n==== %s ====\\n\", nm))\n  for (m in names(b$obj)) {\n    pb <- b$obj[[m]]$adj; pa <- a$obj[[m]]$adj\n    num <- intersect(c(\"surv\", \"se\", \"ci_lower\", \"ci_upper\"), names(pb))\n    cat(sprintf(\"curve %-6s rows %d vs %d | same time/group keys: %s | max|diff| %s\\n\", m, nrow(pb), nrow(pa),\n        identical(pb[c(\"time\", \"group\")], pa[c(\"time\", \"group\")]),\n        paste(sprintf(\"%s=%.1e\", num, sapply(num, function(k) max(abs(pb[[k]] - pa[[k]]), na.rm = TRUE))), collapse = \" \")))\n  }\n  for (k in names(b$UM)) cat(sprintf(\"UM %-12s identical: %s\\n\", k, identical(b$UM[[k]], a$UM[[k]])))\n  if (!is.null(b$Mul)) for (k in names(b$Mul)) cat(sprintf(\"Mul %-11s identical: %s\\n\", k, identical(b$Mul[[k]], a$Mul[[k]])))\n  ae <- all.equal(strip(b), strip(a))\n  cat(\"all.equal(whole cat, minus obj$call):\", if (isTRUE(ae)) \"TRUE\" else paste(head(ae, 5), collapse = \" || \"), \"\\n\")\n  cb <- names(b$obj$direct$call); ca <- names(a$obj$direct$call)\n  cat(\"obj$direct$call args added:\", paste(setdiff(ca, cb), collapse = \", \"), \"\\n\")\n}\n\n## ==== 第 2 段：方案 B 的取点方式评估（grid_eval.R，已含方案 A）\n\nsuppressPackageStartupMessages(library(RegR)); pdf(NULL)\nbase <- readRDS(\"base_rpa.rds\")\nfit_obj <- function(d, times) {\n  invisible(gc(reset = TRUE)); sink(nullfile())\n  t <- system.time(o <- suppressWarnings(RegR:::.get.obj(d, \"group\", \"Sex\", method = \"direct\",\n         times = times, allow_fallback = FALSE)))[[\"elapsed\"]]\n  sink(); list(t = t, mb = sum(gc()[, 6]), adj = o$adj)\n}\ndev <- function(full, grid) {   # drawn line = linear interpolation between points (steps = FALSE)\n  out <- sapply(split(full, full$group), function(f) {\n    g <- grid[grid$group == f$group[1], ]; f <- f[f$time <= max(g$time), ]\n    sapply(c(\"surv\", \"ci_lower\", \"ci_upper\"), function(k)\n      max(abs(stats::approx(g$time, g[[k]], xout = f$time, ties = \"ordered\")$y - f[[k]]), na.rm = TRUE))\n  })\n  apply(out, 1, max)\n}\nset.seed(2026)\nfor (n in c(4387, 30000, 50000)) {\n  d  <- if (n == nrow(base)) base else base[sample.int(nrow(base), n, replace = TRUE), ]\n  et <- sort(unique(d$time[d$DSS == 1]))\n  grids <- list(\n    even50 = seq(0, max(et), length.out = 50),\n    thin50 = c(0, et[unique(round(seq(1, length(et), length.out = 49)))]),\n    even25 = seq(0, max(et), length.out = 25)\n  )\n  full <- fit_obj(d, NULL)\n  message(sprintf(\"n=%6d full   (%3d times)  %6.2f s  peak %6.0f MB\", n, length(unique(full$adj$time)), full$t, full$mb))\n  for (gn in names(grids)) {\n    r <- fit_obj(d, grids[[gn]]); dv <- dev(full$adj, r$adj)\n    # exact at shared time points?\n    m <- merge(full$adj, r$adj, by = c(\"time\", \"group\"))\n    message(sprintf(\"n=%6d %-6s (%3d times)  %6.2f s  peak %6.0f MB | max line dev surv=%.4f ci_lo=%.4f ci_hi=%.4f | shared pts=%d exact=%s\",\n      n, gn, length(grids[[gn]]), r$t, r$mb, dv[\"surv\"], dv[\"ci_lower\"], dv[\"ci_upper\"],\n      nrow(m), isTRUE(all.equal(m$surv.x, m$surv.y)) && isTRUE(all.equal(m$ci_lower.x, m$ci_lower.y))))\n  }\n}\n\n## ---- 第 2 段对比图（grid_plot.R → grid-compare.png）\n\nsuppressPackageStartupMessages({library(RegR); library(ggplot2)}); pdf(NULL)\nd <- readRDS(\"base_rpa.rds\"); et <- sort(unique(d$time[d$DSS == 1]))\nget <- function(times, lab) { sink(nullfile()); o <- suppressWarnings(RegR:::.get.obj(d, \"group\", \"Sex\",\n  method = \"direct\", times = times, allow_fallback = FALSE)); sink(); cbind(o$adj, grid = lab) }\nx <- rbind(get(NULL, \"full (158 pts)\"),\n           get(c(0, et[unique(round(seq(1, length(et), length.out = 49)))]), \"thin50 (event-time quantiles)\"),\n           get(seq(0, max(et), length.out = 50), \"even50 (equal spacing)\"))\nx$grid <- factor(x$grid, levels = unique(x$grid))\np <- ggplot(x, aes(time, surv, colour = grid, linetype = grid)) +\n  geom_ribbon(data = subset(x, grid == \"full (158 pts)\"), aes(ymin = ci_lower, ymax = ci_upper),\n              fill = \"grey70\", alpha = 0.35, colour = NA, show.legend = FALSE) +\n  geom_line(linewidth = 0.5) + facet_wrap(~ group, ncol = 4) +\n  scale_colour_manual(values = c(\"black\", \"#D62728\", \"#1F77B4\")) +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\", \"dotted\")) +\n  scale_x_continuous(breaks = seq(0, 240, 60)) +\n  labs(x = \"Months\", y = \"Adjusted survival (direct, Cox ~ group + Sex)\", colour = NULL, linetype = NULL,\n       title = \"Direct-adjusted curves: full event-time grid vs 50-point grids (n = 4387, grey = full 95% CI)\") +\n  theme_bw(base_size = 10) + theme(legend.position = \"top\")\nggsave(\"grid_compare.png\", p, width = 11, height = 7.5, dpi = 150, bg = \"white\")\n\n## ==== 第 3 段：方案 B，Cox / CSC / FGR get_cat 前后对比（ab2_run.R <before|after>）\n\n# Usage: Rscript ab2_run.R <tag>   (before | after)\ntag <- commandArgs(TRUE)[1]\nsuppressPackageStartupMessages(library(RegR)); pdf(NULL)\nif (!file.exists(\"base2.rds\")) {\n  data(seer_thyroid_mtc_2026, package = \"RegR\")\n  sink(nullfile()); res <- suppressWarnings(get_rpa(seer_thyroid_mtc_2026, c(\"Age\", \"T_stage\"),\n                                                    adj_var = \"Sex\", surv = TRUE)); sink()\n  b <- as.data.frame(res$dat)[, c(\"time\", \"DSS\", \"event\", \"status\", \"group\", \"Sex\", \"Age\")]\n  saveRDS(b[stats::complete.cases(b), ], \"base2.rds\")\n}\nbase <- readRDS(\"base2.rds\")\nset.seed(2026); big <- base[sample.int(nrow(base), 30000, replace = TRUE), ]\ncases <- list(\n  cox_n4387     = list(d = base, surv = TRUE),\n  cox_n30000    = list(d = big,  surv = TRUE),\n  cif_csc_n4387 = list(d = base, surv = FALSE, cif_args = list(model = \"CSC\")),\n  cif_fgr_n4387 = list(d = base, surv = FALSE)\n)\nfor (nm in names(cases)) {\n  cs <- cases[[nm]]\n  args <- list(cs$d, cat_var = \"group\", adj_var = \"Sex\", surv = cs$surv, timepoint = 120)\n  if (!is.null(cs$cif_args)) args$cif_args <- cs$cif_args\n  sink(nullfile()); set.seed(11)\n  t <- system.time(res <- suppressWarnings(do.call(get_cat, args)))[[\"elapsed\"]]\n  sink()\n  saveRDS(res, sprintf(\"%s2_%s.rds\", tag, nm))\n  message(sprintf(\"[%s] %-14s get_cat %7.2f s  direct pts=%d\", tag, nm, t,\n                  length(unique(res$cat$obj$direct$adj$time))))\n}\n\n## ---- 第 3 段比较（ab2_compare.R）\n\nfor (nm in c(\"cox_n4387\", \"cox_n30000\", \"cif_csc_n4387\", \"cif_fgr_n4387\")) {\n  b <- readRDS(sprintf(\"before2_%s.rds\", nm))$cat; a <- readRDS(sprintf(\"after2_%s.rds\", nm))$cat\n  val <- intersect(c(\"surv\", \"cif\"), names(b$obj$direct$adj))\n  cols <- intersect(c(val, \"se\", \"ci_lower\", \"ci_upper\"), names(b$obj$direct$adj))\n  fb <- b$obj$direct$adj; fa <- a$obj$direct$adj\n  m <- merge(fb, fa, by = c(\"time\", \"group\"))\n  exact <- sapply(cols, function(k) max(abs(m[[paste0(k, \".x\")]] - m[[paste0(k, \".y\")]]), na.rm = TRUE))\n  line <- sapply(cols[cols != \"se\"], function(k) max(unlist(lapply(split(fb, fb$group), function(f) {\n    g <- fa[fa$group == f$group[1], ]; f <- f[f$time <= max(g$time), ]\n    abs(stats::approx(g$time, g[[k]], xout = f$time, ties = \"ordered\")$y - f[[k]])\n  })), na.rm = TRUE))\n  um <- all(mapply(identical, b$UM, a$UM))\n  cat(sprintf(\"%-14s pts %3d -> %2d | UM tables identical=%s | unadj curve identical=%s\\n\", nm,\n      length(unique(fb$time)), length(unique(fa$time)), um, identical(b$obj$unadj$adj, a$obj$unadj$adj)))\n  cat(sprintf(\"               shared pts max|diff|: %s\\n\", paste(sprintf(\"%s=%.1e\", names(exact), exact), collapse = \" \")))\n  cat(sprintf(\"               drawn-line max dev   : %s\\n\", paste(sprintf(\"%s=%.4f\", names(line), line), collapse = \" \")))\n}\n\n## ==== 第 4 段：方案 A 用于 CSC，直接调 adjustedcif()（csc_probe.R）\n\nsuppressPackageStartupMessages({library(survival); library(prodlim)})\nd <- readRDS(\"base2.rds\"); lv <- levels(d$group)\ncd <- d[, c(\"time\", \"event\", \"group\", \"Sex\")]\nfit <- riskRegression::CSC(Hist(time, event) ~ group + Sex, data = cd); fit$call$data <- cd\net <- sort(unique(d$time[d$event == 1]))\ngrids <- list(full = NULL, grid50 = sort(unique(c(0, et[unique(round(seq(1, length(et), length.out = 48)))], 120))))\ngo <- function(times, ...) { invisible(gc(reset = TRUE))\n  t <- system.time(o <- adjustedCurves::adjustedcif(d, variable = \"group\", ev_time = \"time\", event = \"event\",\n         cause = 1, method = \"direct\", outcome_model = fit, conf_int = TRUE, times = times, ...))[[\"elapsed\"]]\n  list(t = t, mb = sum(gc()[, 6]), adj = o$adj[order(o$adj$group, o$adj$time), ]) }\nfor (g in names(grids)) {\n  a <- go(grids[[g]]); b <- go(grids[[g]], allContrasts = rbind(lv[1], lv[-1]))\n  k <- c(\"cif\", \"se\", \"ci_lower\", \"ci_upper\")\n  message(sprintf(\"CSC %-6s all 55 pairs %6.2f s %5.0f MB | ref-vs-each %6.2f s %5.0f MB | rows %d/%d | max|diff| %.1e\",\n    g, a$t, a$mb, b$t, b$mb, nrow(a$adj), nrow(b$adj),\n    max(abs(as.matrix(a$adj[k]) - as.matrix(b$adj[k])), na.rm = TRUE)))\n}\n\n## ==== 第 6 段：n = 30000 的 CSC get_cat 各步骤耗时（csc_parts.R）\n\nsuppressPackageStartupMessages(library(RegR)); pdf(NULL)\nbase <- readRDS(\"base2.rds\"); set.seed(2026); d <- base[sample.int(nrow(base), 30000, replace = TRUE), ]\net <- sort(unique(d$time[d$event == 1]))\ngrid <- sort(unique(c(0, et[unique(round(seq(1, length(et), length.out = 48)))], 120)))\ncsc <- list(model = \"CSC\")\ncells <- list(\n  curve_AJ_unadj   = function() RegR:::.get.obj(d, \"group\", \"Sex\", method = \"unadj\", times = NULL, surv = FALSE, allow_fallback = FALSE),\n  curve_CSC_direct = function() RegR:::.get.obj(d, \"group\", \"Sex\", method = \"direct\", times = NULL, surv = FALSE, allow_fallback = FALSE, cif_args = csc, direct_times = grid),\n  HR_crr_unadj     = function() RegR:::.get.UM.haz(d, \"group\", adj_var = \"Sex\", surv = FALSE, method = \"unadj\"),\n  HR_crr_direct    = function() RegR:::.get.UM.haz(d, \"group\", adj_var = \"Sex\", surv = FALSE, method = \"direct\"),\n  CIF120_unadj     = function() RegR:::.get.UM.sur(d, \"group\", adj_var = \"Sex\", surv = FALSE, method = \"unadj\", time = 120, cif_args = csc),\n  CIF120_CSC       = function() RegR:::.get.UM.sur(d, \"group\", adj_var = \"Sex\", surv = FALSE, method = \"direct\", time = 120, cif_args = csc)\n)\nfor (nm in names(cells)) {\n  sink(nullfile()); t <- system.time(r <- tryCatch({ cells[[nm]](); \"ok\" }, error = function(e) conditionMessage(e)))[[\"elapsed\"]]; sink()\n  message(sprintf(\"n=30000 %-16s %7.2f s  %s\", nm, t, r))\n}\n```\n:::\n\n",
    "supporting": [
      "rpa-cox-benchmark_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}